# Generated by Django 5.2.4 on 2025-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='owner_id',
            field=models.UUIDField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
