# Generated by Django 5.2.4 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tasks_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=225),
        ),
    ]
