# Generated by Django 5.2.4 on 2025-12-10 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tasks_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='owner_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
