# Generated by Django 5.2.4 on 2025-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tasks_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
