# Generated by Django 5.2.4 on 2025-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tasks_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user_name',
            field=models.CharField(db_index=True, default='sampleuser', max_length=150),
            preserve_default=False,
        ),
    ]
